# Form implementation generated from reading ui file 'D:\Huflit\ANHTTT Huflit\2023-2024\detai\View\ThietKe\signupDialog.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(526, 407)
        self.usernameInput = QtWidgets.QLineEdit(parent=Dialog)
        self.usernameInput.setGeometry(QtCore.QRect(180, 120, 261, 22))
        self.usernameInput.setObjectName("usernameInput")
        self.passwordInput2 = QtWidgets.QLineEdit(parent=Dialog)
        self.passwordInput2.setGeometry(QtCore.QRect(180, 225, 201, 22))
        self.passwordInput2.setInputMask("")
        self.passwordInput2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordInput2.setObjectName("passwordInput2")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(90, 226, 91, 16))
        self.label_4.setObjectName("label_4")
        self.cancelButton = QtWidgets.QPushButton(parent=Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(300, 300, 93, 28))
        self.cancelButton.setObjectName("cancelButton")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(200, 40, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.passwordInput = QtWidgets.QLineEdit(parent=Dialog)
        self.passwordInput.setGeometry(QtCore.QRect(180, 169, 201, 22))
        self.passwordInput.setInputMask("")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 120, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 170, 91, 16))
        self.label_3.setObjectName("label_3")
        self.showPasswordButton = QtWidgets.QPushButton(parent=Dialog)
        self.showPasswordButton.setGeometry(QtCore.QRect(390, 164, 51, 28))
        self.showPasswordButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Huflit\\ANHTTT Huflit\\2023-2024\\detai\\View\\ThietKe\\../Icon/eye.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.showPasswordButton.setIcon(icon)
        self.showPasswordButton.setObjectName("showPasswordButton")
        self.signupButton = QtWidgets.QPushButton(parent=Dialog)
        self.signupButton.setGeometry(QtCore.QRect(180, 300, 93, 28))
        self.signupButton.setObjectName("signupButton")
        self.showPasswordButton2 = QtWidgets.QPushButton(parent=Dialog)
        self.showPasswordButton2.setGeometry(QtCore.QRect(390, 220, 51, 28))
        self.showPasswordButton2.setText("")
        self.showPasswordButton2.setIcon(icon)
        self.showPasswordButton2.setObjectName("showPasswordButton2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "PassWord:"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.label.setText(_translate("Dialog", "Đăng ký"))
        self.label_2.setText(_translate("Dialog", "UserName:"))
        self.label_3.setText(_translate("Dialog", "PassWord:"))
        self.signupButton.setText(_translate("Dialog", "Sign up"))
